import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import type { Booking } from "@/types/booking";

const DEMO_BOOKINGS: Omit<Booking, "id" | "user_id" | "created_at" | "updated_at">[] = [
  {
    client_name: "Sarah Johnson",
    client_email: "sarah@email.com",
    client_phone: "(555) 123-4567",
    service: "Deep Clean",
    scheduled_date: new Date().toISOString().split("T")[0],
    scheduled_time: "09:00:00",
    duration_minutes: 180,
    assigned_cleaner: "Maria Santos",
    status: "confirmed",
    amount: 320,
    payment_status: "unpaid",
    address: "142 Oak Street, Suite 3",
    notes: "Client prefers eco-friendly products. Has two dogs.",
  },
  {
    client_name: "TechHub Office",
    client_email: "admin@techhub.com",
    client_phone: "(555) 234-5678",
    service: "Office Clean",
    scheduled_date: new Date().toISOString().split("T")[0],
    scheduled_time: "10:30:00",
    duration_minutes: 120,
    assigned_cleaner: "James Lee",
    status: "in_progress",
    amount: 450,
    payment_status: "unpaid",
    address: "88 Innovation Blvd, Floor 4",
    notes: "After-hours access code: 4521. Clean conference rooms first.",
  },
  {
    client_name: "Emily Chen",
    client_email: "emily.chen@gmail.com",
    client_phone: "(555) 345-6789",
    service: "Regular Clean",
    scheduled_date: new Date().toISOString().split("T")[0],
    scheduled_time: "13:00:00",
    duration_minutes: 90,
    assigned_cleaner: "Ava Rodriguez",
    status: "confirmed",
    amount: 180,
    payment_status: "paid",
    address: "305 Maple Avenue, Apt 12B",
    notes: null,
  },
  {
    client_name: "Mark Davis",
    client_email: "mark.d@outlook.com",
    client_phone: "(555) 456-7890",
    service: "Move-out Clean",
    scheduled_date: (() => { const d = new Date(); d.setDate(d.getDate() + 1); return d.toISOString().split("T")[0]; })(),
    scheduled_time: "15:00:00",
    duration_minutes: 240,
    assigned_cleaner: "Maria Santos",
    status: "pending",
    amount: 520,
    payment_status: "unpaid",
    address: "17 Birch Lane",
    notes: "3-bedroom apartment. Carpets need steam cleaning.",
  },
  {
    client_name: "GreenLeaf Co.",
    client_email: "ops@greenleaf.co",
    client_phone: "(555) 567-8901",
    service: "Weekly Office Clean",
    scheduled_date: (() => { const d = new Date(); d.setDate(d.getDate() - 1); return d.toISOString().split("T")[0]; })(),
    scheduled_time: "08:00:00",
    duration_minutes: 150,
    assigned_cleaner: "James Lee",
    status: "completed",
    amount: 380,
    payment_status: "paid",
    address: "900 Park Row, Suite 200",
    notes: "Recurring weekly. Restrooms + kitchen priority.",
  },
  {
    client_name: "Lisa Park",
    client_email: "lisa.park@yahoo.com",
    client_phone: "(555) 678-9012",
    service: "Deep Clean",
    scheduled_date: (() => { const d = new Date(); d.setDate(d.getDate() + 2); return d.toISOString().split("T")[0]; })(),
    scheduled_time: "11:00:00",
    duration_minutes: 180,
    assigned_cleaner: "Ava Rodriguez",
    status: "confirmed",
    amount: 340,
    payment_status: "unpaid",
    address: "72 Elm Drive",
    notes: "First-time client. Full walkthrough needed.",
  },
  {
    client_name: "David Wright",
    client_email: "d.wright@email.com",
    client_phone: "(555) 789-0123",
    service: "Post-Construction Clean",
    scheduled_date: (() => { const d = new Date(); d.setDate(d.getDate() + 3); return d.toISOString().split("T")[0]; })(),
    scheduled_time: "09:30:00",
    duration_minutes: 300,
    assigned_cleaner: "Maria Santos",
    status: "pending",
    amount: 750,
    payment_status: "unpaid",
    address: "45 Cedar Court",
    notes: "Renovation just completed. Heavy dust removal required.",
  },
  {
    client_name: "Bright Smiles Dental",
    client_email: "office@brightsmiles.com",
    client_phone: "(555) 890-1234",
    service: "Medical Office Clean",
    scheduled_date: (() => { const d = new Date(); d.setDate(d.getDate() - 2); return d.toISOString().split("T")[0]; })(),
    scheduled_time: "18:00:00",
    duration_minutes: 120,
    assigned_cleaner: "James Lee",
    status: "completed",
    amount: 420,
    payment_status: "paid",
    address: "221 Health Center Dr",
    notes: "HIPAA compliant cleaning. Sterilization protocol required.",
  },
  {
    client_name: "Amanda Foster",
    client_email: "amanda.f@gmail.com",
    client_phone: "(555) 901-2345",
    service: "Regular Clean",
    scheduled_date: (() => { const d = new Date(); d.setDate(d.getDate() + 4); return d.toISOString().split("T")[0]; })(),
    scheduled_time: "14:00:00",
    duration_minutes: 90,
    assigned_cleaner: "Ava Rodriguez",
    status: "confirmed",
    amount: 160,
    payment_status: "unpaid",
    address: "88 Sunset Blvd, Unit 5",
    notes: null,
  },
  {
    client_name: "Metro Cowork",
    client_email: "hello@metrocowork.com",
    client_phone: "(555) 012-3456",
    service: "Office Clean",
    scheduled_date: new Date().toISOString().split("T")[0],
    scheduled_time: "17:00:00",
    duration_minutes: 150,
    assigned_cleaner: "James Lee",
    status: "cancelled",
    amount: 350,
    payment_status: "unpaid",
    address: "500 Commerce St, Floor 2",
    notes: "Client cancelled — rescheduling for next week.",
  },
];

export async function seedBookingsIfEmpty(userId: string) {
  const { data, error } = await supabase
    .from("bookings")
    .select("id")
    .eq("user_id", userId)
    .limit(1);

  if (error || (data && data.length > 0)) return;

  const rows = DEMO_BOOKINGS.map((b) => ({ ...b, user_id: userId }));
  await supabase.from("bookings").insert(rows);
}
